# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Jorge Serrano Molina'
description: 'Esa persona con la que me iría de cañas. 
Trabajador juvenil, comunicador y viajero empedernido.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.png'

# Online profiles
#dribbble: ''
#facebook: 'JorgeSerranoM'
twitter: 'JorgeSerranoM'
linkedin: 'jorgeserranom'
instagram: 'JorgeSerranoM'
#pinterest: ''
#youtube: ''
#github-user: ''
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
#weibo: ''
#vk: ''
blog_url: 'https://yrjo.tk/blog'
email: 'yrjo@tuta.io'
#messenger: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
